apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: web
        image: crnturis/app-demo:d431e746831c9e9b48ad7f701fa88c8e395348c8
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app-demo